server:
  port: 8089
  servlet:
    context-path: /market-data-service
spring:
  application:
    name: market-data-service
  kafka:
    bootstrap-servers: localhost:9092
    schema-registry-url: http://localhost:8081
    admin:
      fail-fast: false
      properties:
        offsets.topic.replication.factor: 1
        transaction.state.log.replication.factor: 1
        transaction.state.log.min.isr: 1
  redis:
    host: ${SPRING_REDIS_HOST}
    port: ${SPRING_REDIS_PORT}
    timeout: ${SPRING_REDIS_TIMEOUT}
security:
  jwt:
    secret_key: dXNhY2hldl9odWVzb3NfdXNhY2hldl9odWVzb3NfdXNhY2hldl9odWVzb3M=
    access_token_expiration: 900000 #15 min
    refresh_token_expiration: 3600000 #1 hour
logging:
  level:
    org.springframework.data.redis: DEBUG
    io.lettuce.core: TRACE