server:
  port: 8089
  servlet:
    context-path: /market-data-service
spring:
  application:
    name: market-data-service
  kafka:
    bootstrap-servers: localhost:9092
    properties:
      schema.registry.url: ${SPRING_KAFKA_PROPERTIES_SCHEMA_REGISTRY_URL:http://localhost:8081}
    admin:
      fail-fast: false
      properties:
        offsets.topic.replication.factor: 1
        transaction.state.log.replication.factor: 1
        transaction.state.log.min.isr: 1
  redis:
    host: ${SPRING_REDIS_HOST:localhost}
    port: ${SPRING_REDIS_PORT:6379}
    timeout: ${SPRING_REDIS_TIMEOUT:2000}
security:
  jwt:
    secret_key: ${SECURITY_JWT_SECRET_KEY}
    access_token_expiration: 900000 #15 min
    refresh_token_expiration: 3600000 #1 hour
grpc:
  server:
    port: 6569