CREATE TABLE portfolio_cash (
    id BIGINT PRIMARY KEY GENERATED ALWAYS AS IDENTITY,
    portfolio_id BIGINT NOT NULL REFERENCES portfolio(id),
    currency VARCHAR(10) NOT NULL DEFAULT 'RUB',
    available_amount DECIMAL(18,2) NOT NULL DEFAULT 0,
    blocked_amount DECIMAL(18,2) NOT NULL DEFAULT 0,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);