apiVersion: v1
kind: Service
metadata:
  name: clickhouse-service
spec:
  selector:
    app: clickhouse
  ports:
    - protocol: TCP
      port: 8123
      targetPort: 8123
      name: http
    - protocol: TCP
      port: 9000
      targetPort: 9000
      name: native
    - protocol: TCP
      port: 9009
      targetPort: 9009
      name: interserver
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: clickhouse-pvc
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 3Gi
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: clickhouse-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: clickhouse
  template:
    metadata:
      labels:
        app: clickhouse
    spec:
      containers:
        - name: clickhouse
          image: clickhouse/clickhouse-server:23.3-alpine
          ports:
            - containerPort: 8123
            - containerPort: 9000
            - containerPort: 9009
          volumeMounts:
            - name: clickhouse-data
              mountPath: /var/lib/clickhouse
          env:
            - name: CLICKHOUSE_USER
              value: "default"
            - name: CLICKHOUSE_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: clickhouse-secret
                  key: CLICKHOUSE_PASSWORD
            - name: CLICKHOUSE_DB
              value: "analytic_wolfstreet"
      volumes:
        - name: clickhouse-data
          persistentVolumeClaim:
            claimName: clickhouse-pvc