server:
  port: 8080
  servlet:
    context-path: /user-service
spring:
  application:
    name: user-service
  datasource:
    url: jdbc:postgresql://localhost:5432/user_service
    username: postgres
    password: 123456
    driverClassName: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: none
    open-in-view: true
    show-sql: true
  liquibase:
    enabled: true
    change-log: classpath:/db/changelog/db.changelog-master.yaml
  kafka:
    bootstrap-servers: localhost:9092
    admin:
      fail-fast: false
      properties:
        offsets.topic.replication.factor: 1
        transaction.state.log.replication.factor: 1
        transaction.state.log.min.isr: 1
    topic:
      user-created: user-created
s3:
  key_id: ${S3_KEY_ID}
  secret_key: ${S3_SECRET_KEY}
  region: ru-central1
  endpoint: https://storage.yandexcloud.net
  bucket: wolfstreet
security:
  jwt:
    secret_key: dXNhY2hldl9odWVzb3NfdXNhY2hldl9odWVzb3NfdXNhY2hldl9odWVzb3M=
    access_token_expiration: 900000 #15 min
    refresh_token_expiration: 3600000 #1 hour
