CREATE TABLE instruments (
    instrument_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    ticker VARCHAR(255) NOT NULL,
    title VARCHAR(255) NOT NULL,
    CONSTRAINT uk_instruments_ticker UNIQUE (ticker)
);