apiVersion: v1
kind: Service
metadata:
  name: market-data-service
spec:
  selector:
    app: market-data-service
  ports:
    - protocol: TCP
      port: 8089
      targetPort: 8089
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: market-data-service-configmap
data:
  SPRING_KAFKA_BOOTSTRAP_SERVERS: kafka-service:9092
  SPRING_KAFKA_PROPERTIES_SCHEMA_REGISTRY_URL: http://schema-registry-service:8081
  SPRING_APPLICATION_NAME: market-data-service
  SPRING_REDIS_HOST: redis-service
  SPRING_REDIS_PORT: 6379
  SPRING_REDIS_TIMEOUT: 2000
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: market-data-service-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: market-data-service
  template:
    metadata:
      labels:
        app: market-data-service
    spec:
      containers:
        - name: market-data-service
          image: market-data-service:0.0.1-SNAPSHOT
          ports:
            - containerPort: 8089
          envFrom:
            - configMapRef:
                name: market-data-service-configmap
            - secretRef:
                name: jwt-secret


