apiVersion: v1
kind: Service
metadata:
  name: matching-engine
spec:
  selector:
    app: matching-engine
  ports:
    - protocol: TCP
      port: 8087
      targetPort: 8087
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: matching-engine-configmap
data:
  SPRING_KAFKA_BOOTSTRAP_SERVERS: kafka-service:9092
  SPRING_KAFKA_PROPERTIES_SCHEMA_REGISTRY_URL: http://schema-registry-service:8081
  SPRING_APPLICATION_NAME: matching-engine
  SPRING_REDIS_HOST: redis-service
  SPRING_REDIS_PORT: '6379'
  SPRING_REDIS_TIMEOUT: '2000'
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: matching-engine-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: matching-engine
  template:
    metadata:
      labels:
        app: matching-engine
    spec:
      containers:
        - name: matching-engine
          image: matching-engine:0.0.1-SNAPSHOT
          ports:
            - containerPort: 8087
          envFrom:
            - configMapRef:
                name: matching-engine-configmap
            - secretRef:
                name: jwt-secret
