apiVersion: v1
kind: Service
metadata:
  name: order-service
spec:
  selector:
    app: order-service
  ports:
    - protocol: TCP
      port: 8085
      targetPort: 8085
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: order-service-configmap
data:
  SPRING_DATASOURCE_URL: jdbc:postgresql://postgres-service:5432/order_service
  SPRING_KAFKA_BOOTSTRAP_SERVERS: kafka-service:9092
  SPRING_KAFKA_PROPERTIES_SCHEMA_REGISTRY_URL: http://schema-registry-service:8081
  GRPC_CLIENT_PORTFOLIO-SERVICE_ADDRESS: static://portfolio-service:6565
  SPRING_APPLICATION_NAME: order-service
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: order-service-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: order-service
  template:
    metadata:
      labels:
        app: order-service
    spec:
      containers:
        - name: order-service
          image: order-service:0.0.1-SNAPSHOT
          ports:
            - containerPort: 8085
          envFrom:
            - configMapRef:
                name: order-service-configmap
            - secretRef:
                name: jwt-secret
          env:
            - name: SPRING_DATASOURCE_USERNAME
              valueFrom:
                secretKeyRef:
                  name: postgres-secret
                  key: POSTGRES_USER
            - name: SPRING_DATASOURCE_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: postgres-secret
                  key: POSTGRES_PASSWORD
