apiVersion: v1
kind: Service
metadata:
  name: portfolio-service
spec:
  selector:
    app: portfolio-service
  ports:
    - name: http
      protocol: TCP
      port: 8083
      targetPort: 8083
    - name: grpc
      protocol: TCP
      port: 6565
      targetPort: 6565
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: portfolio-service-configmap
data:
  SPRING_DATASOURCE_URL: jdbc:postgresql://postgres-service:5432/portfolio_service
  SPRING_KAFKA_BOOTSTRAP_SERVERS: kafka-service:9092
  SPRING_KAFKA_PROPERTIES_SCHEMA_REGISTRY_URL: http://schema-registry-service:8081
  GRPC_SERVER_PORT: '6565'
  SERVER_PORT: '8083'
  SPRING_APPLICATION_NAME: portfolio-service
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: portfolio-service-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: portfolio-service
  template:
    metadata:
      labels:
        app: portfolio-service
    spec:
      containers:
        - name: portfolio-service
          image: portfolio-service:0.0.1-SNAPSHOT
          ports:
            - containerPort: 8083
            - containerPort: 6565
          envFrom:
            - configMapRef:
                name: portfolio-service-configmap
            - secretRef:
                name: jwt-secret
          env:
            - name: SPRING_DATASOURCE_USERNAME
              valueFrom:
                secretKeyRef:
                  name: postgres-secret
                  key: POSTGRES_USER
            - name: SPRING_DATASOURCE_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: postgres-secret
                  key: POSTGRES_PASSWORD
